### ISSUE TITLE
CSW management and harvesting have errors

### ISSUE THREAD

**Issue by armin11** [mrmap-community/mrmap#112]
### Environment
* Python version: 3.7
* MrMap version: pre 1.0

### Steps to Reproduce
1. Try to register CSW interfaces
2. Try to start harvesting process
3. Examples can be found here (all german CSW interfaces, which are aggregated by the central german CSW): https://gdk.gdi-de.org/gdk_harvesting/

### Expected Behavior

- All CSW should be registerable
- Each CSW interface should be harvested on demand

### Observed Behavior
Many CSW cannot be registered
Most harvesting processes leads to errors
...

**Comment by jokiefer** [comment]
fixed in #113
