### ISSUE TITLE
Improve the Dev Setup

### ISSUE THREAD

**Issue by Unraveler** [mrmap-community/mrmap#143]
### Environment
* Python version:  3.7+
* MrMap version: dev

### Proposed Functionality
- [x] Make the dev setup simpler, adding celery and the app to also run together with docker
- [x] Automate way to get the files for the Inpsire validator container (currently in the [artefact repository](https://github.com/mrmap-community/artefacts) (done in #172)
- [x] Document how to add the new python enviroment in the PyCharm IDE
- [x] Document how to debug using PyCharm IDE
- [x] move doker setup folder to the root of the repo (done in #163)
- [x] add default pycharm run configurations to repo (done in e6b519d722e3795f19e9701770e23233fe3f4111)

### Use Case
A developer wants to start working as soon as possible without any hassles  or too many steps until he can start developing

### Database Changes
None

### External Dependencies
None

**Comment by jokiefer** [comment]
todo:
* [ ] pycharm setup docu
* [ ] environment docu
* [ ] docker application stack docu
* [ ] maintenane docker container/volumes
