### ISSUE TITLE
MapContext: Finish basic CRUD workflow in UI (create, list, edit, delete)

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#149]
### Environment
* Python version: 3.7+
* MrMap version:  1.0-pre

### Proposed Functionality

- [x] Created MapContext resources shall be listed in list view
- [x] Created MapContext resources can be deleted
- [x] Created MapContext resources can be edited

### Use Case

User wants to perform basic MapContext-related tasks

### Database Changes
Probably none.

### External Dependencies
None.

**Comment by jokiefer** [comment]
merged in #174 - close this
