### ISSUE TITLE
Docker Image for Developers

### ISSUE THREAD

**Issue by jokiefer** [mrmap-community/mrmap#18]
Greetings!

I just remembered the last meeting when the possibility of a development container beeing created was mentioned. 

Is that still planned?

**Comment by jokiefer** [comment]
joki commented 2 months ago
Owner

@hollsandre whats about a demo vm?
hollsandre commented 2 months ago
Owner

@joki i could do that,
@SvenLVGL what do you exactly mean by a development container? with docker?
SvenLVGL commented 2 months ago
Poster

    @hollsandre whats about a demo vm?

That’s a different topic.

    @joki i could do that,
    @SvenLVGL what do you exactly mean by a development container? with docker?

Yes, Docker would be the obvious option, I don’t really care though what it’s build with.

You should not have to work on this though. I asked because someone mentioned in the last development meeting that a container might be created. I just wanted to know the current state. It was meant to allow easy access for any contributors. That way a certain issue could be assigned to a developer and he could start working right away.
joki commented 1 month ago
Owner

@SvenLVGL take a look on #113. Maybe we should add it again.
jansule commented 1 month ago

We also added a very basic docker setup in https://git.osgeo.org/gitea/GDI-RP/MrMap/pulls/483. So this might also be interesting to look at.
SvenLVGL commented 1 month ago
Poster

    We also added a very basic docker setup in https://git.osgeo.org/gitea/GDI-RP/MrMap/pulls/483. So this might also be interesting to look at.

Thank you for the hint. I didn’t know about that discussion.

I would desire a setup for dev only. I don’t think many of the targeted infrastructures use containerized software in production. We sure don’t.

The pros of a dev container to me personally are the following:

    easy start for new developers especially if they are contractors that just get some issues assigned
    the “build” process can be tested
    The actual build or installation process does not seem to be tested. Therefor we only know that a change doesn’t brake the running system, not if you could still install it.
    If you build a new container and it doesn’t build or run properly you know straight away that you gotta revert the changes or adjust the installation process.

👍 1
SvenLVGL changed title from Development Container to Docker Image for Developers 1 month ago
SvenLVGL commented 1 month ago
Poster

@jansule the docker-compose code in cd1d9bd31d/docker/docker-compose-dev.yml looks pretty much like what I was looking for.

Did it contain no container for the actual MrMap Django project?
jansule commented 1 month ago

If I remember correctly, I had some problems with the PyCharm debugger in combination with a Django docker container, which I could not solve within the time I had.

But it should be worth to take another look at it, and try to get it up and running.

There will probably be a few other things to add, e.g. a container for each celery process.

In https://git.osgeo.org/gitea/GDI-RP/MrMap/pulls/121 I also created a dedicated compose file that uses mapserver instead of geoserver. If that is of interest, it might be a good starting point.

**Comment by SvenTUM** [comment]
We should consider adding this to an earlier point.

I think this could speed up and ease the development process and therefor it's worth more the earlier we get it functioning.

**Comment by jokiefer** [comment]
@SvenTUM feel free to do it. I'am stuck with some other main features and housekeeping issues.

**Comment by SvenTUM** [comment]
@jokiefer I will have a look at it. So far I could not even get it to run though. 
One installation has problems with celery running, and a local clone can't even pip install the requirements.txt without failing.

Could you check if the requirements.txt matches exactly your pip freeze results?

**Comment by jokiefer** [comment]
take a look on #64
This issue is still open. You could do it first (if you want). Just checkout the current master and run `pip freeze > requirements.txt`
