### ISSUE TITLE
MapContext/Layer: Add preview Image to model and upload functionality

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#192]
### Environment
* Python version: 3.7+
* MrMap version: 1.0-pre

### Proposed Functionality
Similar to `DatasetMetadata`, `MapContext` and `Layer` instances should allow for preview images.

### Use Case
A user edits a `MapContext` and clicks "Select File" to upload a local image file.

### Database Changes
`MapContext` and `Layer`require a new field `preview_image` of type `ImageField`.

### External Dependencies
None.

**Comment by Unraveler** [comment]
I just noticed that `Layer` should also have a `preview_image`. That was implemented only on `MapContextLayer`. I'll do it in a separate MR and will then close this issue
