### ISSUE TITLE
MapContext: Add filtering to Layer field using DatasetMetadata as a filter parameter (followup to #150)

### ISSUE THREAD

**Issue by Unraveler** [mrmap-community/mrmap#223]
### Environment
* Python version:  3.7+
* MrMap version: 1.0pre

### User Story
This ticket is a follow up ticket to #150 
As a user, I want to be able to select the layer associated to my selected dataset metadata in the create MapContext form, without guessing which one belongs to my selected dataset metadata.

This has been previously done, and some of the code necessary is already commented out (see  PR #196 ). Unfortunately, despite the fact the filtering was working, the form was not submitting. This was likely caused by the (now commented) jquery code in the MapContextForm template, which needs to be refactored/redone.

### Acceptance criteria
* [x] The Layer form field options to selected have been filtered according to the selected Dataset Metadata.
* [x] Filtering should filter the correct form field added MapContextLayer nodes (since it is an inline form, each form field will be identified by an id)
* [x] For submits without any issue

**Comment by jokiefer** [comment]
duplicated to #245
