### ISSUE TITLE
SearchInterface: allow ordering

### ISSUE THREAD

**Issue by jokiefer** [mrmap-community/mrmap#241]

**Comment by MrSnyder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-team-6154105429f6f500168703ce/issues/mrmap-community/mrmap/241?planning-poker) with ZenHub @jokiefer @Unraveler

**Comment by MrSnyder** [comment]
Tasks

- [ ] Use [OrderingFilter](https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter) for service API view
- [ ] Do the same for layer, feature type, dataset metadata, mapcontext
- [ ] Test
