### ISSUE TITLE
Map Context: API endpoint

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#244]
- Note that [OWSLib](https://github.com/geopython/OWSLib) already has a partial implementation of OWS Context serialization that supports both GeoJSON and ATOM encodings. We may want to build upon this.
- Also, [GeoDjango](https://docs.djangoproject.com/en/3.2/ref/contrib/gis/serializers/) supports serialization to GeoJSON, which may also be an interesting option.

### User Story
As an API client, I want to be able to download mapcontext documents according to the [OGC OWS Context GeoJSON Encoding Standard](https://www.ogc.org/standards/owc), so that I can initialize a map view with a hierachy of wms layers.

### Acceptance criteria
* [x] Given I am an API client, when I access a Map Context resource, I want that the HTTP response is a JSON document that follows the OWS Context specification.
* [x] Given I am an API client, when I try to access a non-existing Map Context resource, I want that the HTTP response is 404.
* [x] Given I am an API client, when I access a Map Context resource that defines a layer tree, I want that the returned OWS context document contains an exact representation of the layer tree.

**Comment by Unraveler** [comment]
Thanks @armin11 , that is really helpfull :+1:
