### ISSUE TITLE
Create a metadata detail HTML view

### ISSUE THREAD

**Issue by Don-King-Kong** [mrmap-community/mrmap#264]
A metadata detail view is to be created.
A form should be created that allows editing and saving metadata, similar to the metadata editor in Mapbender.

see the following image

[metadateneditor.JPG](https://images.zenhubusercontent.com/618108c1aff73613e8cd5dbd/85d6ad69-bb07-4c12-a486-02b749d5b474)

greetings
Yakup

**Comment by jokiefer** [comment]
Backend supporting this under the specific service endpoints. For example to edit wms use `/api/v1/registry/wms/{id}/` endpoint.
