### ISSUE TITLE
Backend: Login-endpoint responds unexpectedly to an invalid username/password pair

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#268]
### Environment
* Python version: 3.8.10
* MrMap version: commit 8c860aca85b12d5fabb43212b38890ee53b803c6

### Steps to Reproduce
1. Go to https://localhost/login
2. Open Developer Tools in Browser -> Network tab
3. Login using foo / bar
4. Check response code and response of request against `login/` endpoint

### Expected Behavior
Backend should respond with response code 403 and possibly some kind of error message.

### Observed Behavior
Backend responds with 200 and an empty `Login` object:

```
{
    "data": {
        "type": "Login",
        "id": null,
        "attributes": {
            "last_login": null,
            "is_superuser": false,
            "username": "",
            "first_name": "",
            "last_name": "",
            "email": "",
            "is_staff": false,
            "is_active": false,
            "date_joined": null,
            "confirmed_newsletter": false,
            "confirmed_survey": false
        }
    }
}
```

**Comment by jokiefer** [comment]
solved and merged
