### ISSUE TITLE
Frontend: Column filtering should adapt to datatype and endpoint capabilities in generic ResourceTable component

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#273]
### Environment
* Python version: 3.8.10
* MrMap version: b23b7e2d74eb6f9690d6a09e33455f428b2e44e1

### User Story
As a developer, I want that the generic `ResourceTable`component adapts to the backend datatypes and filtering capabilities so that the table filtering works in a reasonable and usable way right out-of-the-box.

### Acceptance criteria
* [x] Given I am a developer and I am applying the `ResourceTable` to a backend resource, when I have a non-filterable column, I want that the table does not offer filtering for that column.
* [x] Given I am a developer and I am applying the `ResourceTable` to a backend resource, when I have a filterable date column, I want that the table offers date-picker based filtering for that column.

![2021-11-30_15-12](https://user-images.githubusercontent.com/289590/144063500-b243f59e-c464-41ac-b6cb-f331eb435d8f.png)

**Comment by jokiefer** [comment]
done
