### ISSUE TITLE
Frontend: Map-Context Form Unit Tests

### ISSUE THREAD

**Issue by Unraveler** [mrmap-community/mrmap#286]
These tests should include:
- MapContext component
- MapContextForm component
- MapCOntextLayerForm component

**Comment by jokiefer** [comment]
as discussed in #278 there should be automated QA checks.
create a follow up issue if this one is done or do it in one step, cause this is the first issue which creates tests for the frontend.

**Comment by jokiefer** [comment]
all mapcontext components are reengineered.
