### ISSUE TITLE
Add 'Testorganisation' automatically for dev-setup

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#309]
### Proposed Changes
When starting the `backend` docker container on an empty database, an organisation should be created automatically.

### Justification
Saves time when re-creating the dev-setup.

**Comment by jokiefer** [comment]
this is handled by the `test_users.json`.
to load the fixture in docker setup start the container with entrypoint settings:
```yml
entrypoint: >
  /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
  /opt/mrmap/manage.py loaddata test_users"
```
