### ISSUE TITLE
Frontend: Use useOperationMethod/JsonApiUtils instead of JsonApiRepo classes

### ISSUE THREAD

**Issue by MrSnyder** [mrmap-community/mrmap#424]
### Proposed Changes
The frontend currrently uses a hierarchy of `JsonApiRepo` classes for backend communication. These should be removed and backend calls should be performed using the `useOperationMethod` Hook and/or `JsonApiUtils`.

### Justification
The dynamic nature of our JSON:API backend does not fit very well with a type/class-based repository layer. Using the JSON:API directly seems to be the better approach, allowing flexible backend calls as needed.

**Comment by jokiefer** [comment]
I think this is done since fossgis 2022
