### ISSUE TITLE
Rename Codebase Directory

### ISSUE THREAD

**Issue by jansule** [mrmap-community/mrmap#47]
### Proposed Changes

It would be nice to rename the directory with the codebase from `mrmap` to `src`.

### Justification

It's a widely followed convention.

**Comment by jokiefer** [comment]
hm if we would publish mrmap as pip package the imports in other projects would be like `src.service.models` or i'am wrong?
Are you should that this is a widely followed convention for python packages?

**Comment by SvenTUM** [comment]
> hm if we would publish mrmap as pip package the imports in other projects would be like `src.service.models` or i'am wrong?
> Are you should that this is a widely followed convention for python packages?

I haven't created a PIP package yet. The documentation states, that you define the package name in a file `setup.cfg`. So that should not be a problem.

---

> ### Proposed Changes
> It would be nice to rename the directory with the codebase from `mrmap` to `src`.
> 
> ### Justification
> It's a widely followed convention.

I'm not sure for what kind of Python projects `src` directories are a convention. I haven't heard of it related to Django.
The two conventions I know are having everything in the root directory of the project, or using the applications name (like here).

**Comment by jokiefer** [comment]
> The two conventions I know are having everything in the root directory of the project, or using the applications name (like here).

Since more then one year in development with django, i always seen projects with the root directory name like the application name.

naming the root folder src comes from java developing.

So i would set the status to wontfix and close this issue.

**Comment by jansule** [comment]
> Since more then one year in development with django, i always seen projects with the root directory name like the application name.

There seem to be a few (e.g. [flask](https://github.com/pallets/flask)), but it looks like it is the minority. So you are absolutely right by keeping the directory name as is.
