### ISSUE TITLE
Problem with formtools wizard when registrating services

### ISSUE THREAD

**Issue by armin11** [mrmap-community/mrmap#82]
### Environment
* Python version: 3.7.9
* MrMap version: pre 1.0

### Steps to Reproduce
1. Install from scratch
2. Try to register a service with different browser language settings
3. Go to the second form page

### Expected Behavior

The second form page should be shown - service versions, authentication info, ...

### Observed Behavior
AttributeError at /resource/add

'NoneType' object has no attribute 'get'

http 500 error - the variable from post request is not evaluated, independent from session storage (db or file)

**Comment by armin11** [comment]
Done ;-)

**Comment by jokiefer** [comment]
hilarious.. this would mean, that we got maybe problem in other wizards too. How did you test it ?
